=== GetDKAN/dkan/modules/dkan_harvest/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "harvest-plan",
  "type": "object",
  "title": "Harvest Plan",
  "required": [
    "identifier",
    "extract",
    "load"
  ],
  "properties": {
    "identifier": {
      "type": "string",
      "title": "The plan's identifier",
      "pattern": "^(.*)$"
    },
    "extract": {
      "type": "object",
      "title": "Extract",
      "required": [
        "type",
        "uri"
      ],
      "properties": {
        "type": {
          "type": "string",
          "title": "Class utilized to extract the data from the source."
        },
        "uri": {
          "type": "string",
          "title": "The URL or Location of the Source",
          "examples": [
            "http://demo.getdkan.com/data.json"
          ]
        }
      }
    },
    "transforms": {
      "type": "array",
      "title": "The Transforms for the Harvest",
      "additionalProperties": false,
      "items": {
        "type": "string"
      }
    },
    "load": {
      "type": "object",
      "title": "The Load settings for the Harvest",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "title": "Class utilized to load the harvested data."
        }
      }
    }
  }
}

=== GetDKAN/dkan/modules/dkan_sample_content/harvest_plan.json
{
  "identifier": "sample_content",
  "extract": {
    "type": "\\Drupal\\dkan_harvest\\ETL\\Extract\\DataJson",
    "uri": "/dkan_sample_content.json"
  },
  "transforms": ["\\Drupal\\dkan_harvest\\Transform\\ResourceImporter"],
  "load": {
    "type": "\\Drupal\\dkan_harvest\\Load\\Dataset"
  }
}

=== GetDKAN/dkan/modules/dkan_harvest/tests/files/plan.json
{
  "identifier": "test",
  "extract": {
    "type": "\\Drupal\\dkan_harvest\\ETL\\Extract\\DataJson",
    "uri": ""
  },
  "transforms": [
    "\\Drupal\\dkan_harvest\\ETL\\Transform\\AddId",
    "\\Drupal\\dkan_harvest\\ETL\\Transform\\AddRandomNumber"
  ],
  "load": {
    "type": "\\Drupal\\dkan_harvest\\ETL\\Load\\Simple"
  }
}
